### ISSUE TITLE
Add TX indication on GPIO

### ISSUE THREAD

**Issue by vbuitvydas** [myriadrf/LimeSDR-Mini-v2_GW#3]

**Comment by vbuitvydas** [comment]
TXANT_EN indication added to GPIO[0]. 

To enable it, set FPGA register 0x00C0[0]  bit to '0'; 

To control TXANT_EN rising and falling edge delays use FPGA registers: 
0x0010 - TXANT_PRE
0x0011 - TXANT_POST 
By default TXANT_PRE and TXANT_POST registers are set to 0x0001. This means rising and falling edges are delayed by time equal to one period of sample rate. 

![txant_pre_post](https://github.com/myriadrf/LimeSDR-Mini-v2_GW/assets/25218697/7000cee4-5410-403e-b17b-72d3f7a61df8)

**Comment by oe1rsa** [comment]
I have observed that the feature almost works as described with the difference, that the 

- minimum delay TXANT_PRE = 0 switches on almost 10usec before TX begins and
- TXANT_POST = 0 switches of approx 10 usec before of TX.

If I now try to use TXANT_PRE = 33, which is trunc(10e-6*samp_rate) in my case in order to switch on just in time, I can see a small variation between startups, i.e. the delay appears to be later or earlier by about 200nsec.

For the intended use case, PA switching, I believe this behaviour will pose no problems. However, I just wanted to report my findings.
